### ISSUE TITLE
Add a live option

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-replication-stream#2]
like `replication({opts: live})`

**Comment by nolanlawson** [comment]
On second thought, this doesn't make much sense.

**Comment by 6bangs** [comment]
Why not?

**Comment by nolanlawson** [comment]
Because I want to limit the scope of this module. It's already a stream.

**Comment by 6bangs** [comment]
Ok; how would you get a similar behavior without a live option? Call dump repeatedly?

**Comment by nolanlawson** [comment]
No, you'd use the stream directly and then use streams as intended - to progressively load data.
