### ISSUE TITLE
Could this go upstream into PouchDB/CouchDB?

### ISSUE THREAD

**Issue by nickcmaynard** [nolanlawson/pouchdb-replication-stream#34]
We're using this to shorten our initial replication times from remote CouchDB -> in-browser PouchDB (with [pouchdb-load](https://github.com/nolanlawson/pouchdb-load)) from ~120s to 2s.  It's such a massive speedup that I can't help thinking that this component (which I see as server-side) could be in CouchDB/PouchDB trunk.

I guess the answer is philosophical, and the question might be naïve, but could this be pushed upstream?

**Comment by ngbinh** [comment]
@nickcmaynard I am also interested in a way to shorten our initial replication from CouchDB to in browser PouchDB. Can you please share the way you set it up? Thanks

**Comment by nickcmaynard** [comment]
@ngbinh You need an intermediary NodeJS server to run this package (we use exporess-pouchdb-replication-stream as a wrapper).  Then run pouchdb-load in your browser.  The documentation pretty much covers it.

**Comment by nolanlawson** [comment]
This library is kind of a testing ground for a potential new CouchDB API. The code itself wouldn't be used (CouchDB is Erlang; this is JavaScript), but it could definitely influence the design. @janl has been particularly interested in this.

**Comment by kxepal** [comment]
Theoretically, replicator may use such algorithm if it was asked to create target during replication or target docs count is zero. However, this also assumes that there will be no concurrent replication processes, so this feature as an option could be good.

**Comment by nolanlawson** [comment]
Closing, currently no plans to integrate into CouchDB
