### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/pouchdb-replication-stream#42]
Hello, 
when calling a stream from a remoteDB, I have this error : 

```
RangeError: Maximum call stack size exceeded
```

would you tell me how to solve it ?
Thank you very much.

**Comment by ronyrun** [comment]
problem solved it was because of the PouchDB version.

**Comment by nolanlawson** [comment]
should be fixed by fc17211b55037276626d57a8096782ecca4b125d, let me know if not
