### ISSUE TITLE
Error when Dumping a remoteDB stream.

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/pouchdb-replication-stream#44]
on the call of the dump 

```
var remoteStreamDB = new PouchDB("http://localhost:3300/api/couchdb/DBNAME");
remoteStreamDB.dump(stream),
```
the api use express-pouchdb-replication-stream
I encounter this error with PouchDB 5.0.0 or PouchDB 4.0.3

![image](https://cloud.githubusercontent.com/assets/7273443/10416997/757babfc-702d-11e5-9c37-f40b7711531d.png)

**Comment by nolanlawson** [comment]
Sounds like the bug is in express-pouchdb-replication-stream. Maybe @conor-mac-aoidh can help?

Also if you can show the line of code that's throwing, that would be helpful. :)

**Comment by ronyrun** [comment]
It's just the call of remoteStreamDB.dump(stream); from your example.
let me try with the last version of PouchDB.

**Comment by ronyrun** [comment]
OK, then I tested with PouchDB 5.0.0.
and I encounter the same error :
![image](https://cloud.githubusercontent.com/assets/7273443/10434702/763a0b80-711b-11e5-90ef-8a062ba93019.png)


Here is the api code : 

```javascript
var express = require('express');
var repStream = require('express-pouchdb-replication-stream');
var http = require('http');

var app = express();
app.set('port', 3300);

//res.header("Access-Control-Allow-Origin", "*");
app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "http://localhost:8100");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
    res.header("Access-Control-Allow-Credentials", true);
    next();
});

app.use('/api/couchdb/:db', repStream({
    url     : 'https://whenagain:fi9bbskrc@whenagain.cloudant.com',
    dbReq   : true
}));

http.createServer(app).listen(app.get('port'));
```

When using the express api I get the datas without pb : 
![image](https://cloud.githubusercontent.com/assets/7273443/10434800/fdfdb22e-711b-11e5-9400-3886de3c96cd.png)

**Comment by conor-mac-aoidh** [comment]
What is running on the client application?

Can you capture the API response from express when your client application is running?

You could use the web inspector network tab for web apps. Or on NodeJS something like [nock](https://github.com/pgte/nock) would work.

**Comment by ronyrun** [comment]
Hey @conor-mac-aoidh I edited the post with what I run on client side.

**Comment by conor-mac-aoidh** [comment]
Ok. Can you run this in Chrome web inspector? Open the Network tab. Look for the network request to the express API and check that the response is ok.

**Comment by ronyrun** [comment]
On client side I get the datas !

![image](https://cloud.githubusercontent.com/assets/7273443/10435285/4da55d38-711f-11e5-8239-79722899eba4.png)


but it ends with this error 

![image](https://cloud.githubusercontent.com/assets/7273443/10435295/5afd6598-711f-11e5-974c-7d79f70f36c9.png)



When I call remoteStreamDB.dump(stream) on client side

**Comment by conor-mac-aoidh** [comment]
Ok. That looks ok so far.

Can you open the "Response" tab and show the contents?

**Comment by ronyrun** [comment]
I have  nothing on the response tab.

"failed to load response data"

**Comment by conor-mac-aoidh** [comment]
Ok, I think there may be some error happening that is not thrown. And it is probably related to the change I made regarding this issue:
https://github.com/conor-mac-aoidh/express-pouchdb-replication-stream/issues/2

I'm going to publish a new version of express-pouchdb-replication-stream in a few minutes

**Comment by ronyrun** [comment]
I have the exact same error when I use the dumpString exemple 

```javascript
                    console.debug("call remoteStreamDB ", remoteStreamDB);
                    remoteStreamDB.dump(stream)
                        .then(function () {
                            console.log('Yay, I have a dumpedString: ' + dumpedString);
                            deferred.resolve(true);
                        }).catch(function (err) {
                            console.log('oh no an error', err);
                            deferred.resolve(false);
                        });
```

**Comment by ronyrun** [comment]
Ok thank you @conor-mac-aoidh

**Comment by conor-mac-aoidh** [comment]
Ok, please try express-pouchdb-replication-stream@1.0.5

Check if there are any errors this time in the API call. If not, I'm not sure what the issue is.

**Comment by ronyrun** [comment]
OK I'm on it

**Comment by ronyrun** [comment]
Did you update npm ?

**Comment by ronyrun** [comment]
OK I copied the new index.js of your repo.
And same Error with 
"failed to load response data"

**Comment by conor-mac-aoidh** [comment]
Ok, I don't think it is an issue with express-pouchdb-replication-stream

**Comment by ronyrun** [comment]
OK I'll ask @nolanlawson about it.

**Comment by ronyrun** [comment]
thank you for your time

**Comment by ronyrun** [comment]
OK it seems the error occures because the Database is on CLoudant Side...

**Comment by ronyrun** [comment]
Error solved, no need to dump on client side what had been dumped in node side.
