### ISSUE TITLE
Migrating between adapters

### ISSUE THREAD

**Issue by mudcube** [nolanlawson/pouchdb-replication-stream#46]
Nice work on this plugin :+1:  

With it you can also migrate between adapters. I did not notice an example of migrating between adapters in the documentation (perhaps missed it?). This seems to work well, would it be the recommended route?

```js
var stream = new MemoryStream();
var source = new PouchDB('mydb', {adapter: 'websql'});
var dest = new PouchDB('mydb', {adapter: 'idb'});
Promise.all([
	source.dump(stream),
	dest.load(stream)
])
```

**Comment by nolanlawson** [comment]
Cool! That is a very interesting trick, although I believe you could also technically just use `replicate()` to accomplish this:

```js
var source = new PouchDB('mydb', {adapter: 'websql'});
var dest = new PouchDB('mydb', {adapter: 'idb'});
source.replicate.to(dest);
```
