### ISSUE TITLE
e.pipe is not a function error.

### ISSUE THREAD

**Issue by Bassforce86** [nolanlawson/pouchdb-replication-stream#49]
Hi, I've had a hunt around the replication-stream (using the minified version but have pulled down both to check), my JS isn't all that great yet, so it's probably that it is an issue my end, however, Not being able to trace e.pipe back to its origin I can't find what exactly the issue is (assuming it IS the filethat i'm trying to load that is the issue!).

Error log from Browser:
`TypeError: e.pipe is not a function
    at i.<anonymous> (http://idleechoes.co.uk/jkblog/external-scripts/pouchdb.replication-stream.min.js:3719:15)
    at http://idleechoes.co.uk/jkblog/external-scripts/pouchdb.replication-stream.min.js:53:42
    at i.<anonymous> (http://idleechoes.co.uk/jkblog/external-scripts/pouchdb.replication-stream.min.js:48:29)
    at i.load (http://idleechoes.co.uk/jkblog/external-scripts/pouchdb.replication-stream.min.js:37:30)
    at XMLHttpRequest.xhttp.onreadystatechange (http://idleechoes.co.uk/jkblog/blog/new-post.js:355:20)`

If you wish to look at it's implementation feel free to poke around the page, it's only my student project for a module so there is no sensitive data there.

http://idleechoes.co.uk/jkblog/blog/new-post.html

I've had to find a work around because I cannot install CouchDB or Node onto the server, so excuse the quirks!

Many Thanks

James

**Comment by nolanlawson** [comment]
It looks like the bug is that you are using both `pouchdb-load` and `pouchdb-replication-stream` at the same time, in which case the `db.load()` function expects a stream, not a string.

I added a longer note to the readme, so please check it out and let me know if that helps: https://github.com/nolanlawson/pouchdb-replication-stream#warning-when-using-pouchdb-load

**Comment by Bassforce86** [comment]
Thankyou for such a quick response, I've now updated the files accordingly, however, when loading a stream (created from dumped txt file) is always comes in empty/doesn't load but gives the success message. Sorry to bother you with this as i'm sure you're busy.
