### ISSUE TITLE
db.load no return from Promise

### ISSUE THREAD

**Issue by Bassforce86** [nolanlawson/pouchdb-replication-stream#50]
Pouchdb Version 5.1.0
Browserify MemoryStream - latest as of Jan 1st 2016

Please see here: http://idleechoes.co.uk/jkblog/blog/new-post.html

new-post.js: lines 350 -->;
successfully converted string to stream, 
once passed to the db.load, all code halts. 
No returns are given. (I've checked with stream.toString() that the stream does contain data).
No errors reported.

Any ideas? 

Thanks

**Comment by Bassforce86** [comment]
Whilst this was an entertaining endevour into streams, it was far simpler to revert back to loading via pouchdb-load and renaming the plugin call. It still never worked using the previous method, so I would advise against it unless a solution is found.

**Comment by nolanlawson** [comment]
Sounds like maybe you ran into this? https://github.com/nolanlawson/pouchdb-replication-stream#warning-when-using-pouchdb-load

**Comment by Bassforce86** [comment]
No, it wasn't to do with that, at the time these issues were occurring I wasn't using your pouchdb.load library. 

I think it was simply the fact that the string being returned was somehow being corrupted, so when it was being passed into the stream, Pouch was reading in a memory stream (so throwing no error) but the information may have been incomplete in some way. I did notice that at the end of the dumped files there are a few stray newline breaks. I split the file using string.split('\n') parseing each line as a JSON, then joining the strings with a single trailing \n but it was still unhappy, but also not throwing errors. it as very odd.

**Comment by xn** [comment]
@nolanlawson I seem to be running into this. Do you want me to create a new issue or do you want to reopen here?
